### PR TITLE
Fix column modifying on columnstore tables

### LINKED ISSUE #39: Add support for the "change"-function
It would be great if this feature was supported.

As I understand, the following would have to be done in order to change a field (This example changes a field called "name" from a varchar to text):

1. Add a column of the desired type (ALTER TABLE table_name ADD COLUMN field2 TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`; )
3. Fill values in this column with the column you want to change the data type (UPDATE table_name SET name2 = name;)
4. Remove the previous column (ALTER TABLE table_name DROP COLUMN name;)
5. Change the name of the new column (ALTER TABLE table_name CHANGE name2 name;)

Would it be possible to implement this? Or is there already another way to do this?

### PR DESCRIPTION
**Pull request by hafezdivandari**
Fixes #39

Add support for modifying columns on
* columnstore tables - requires Laravel > 11.15
* rowstore tables - requires Laravel > 10.0

Note 1: On Laravel 10.x, You have to call `Schema::useNativeSchemaOperationsIfPossible()` method within the `boot` method of your `App\Providers\AppServiceProvider` class. Not needed on Laravel 11.x

Note 2: I'm not sure how Singlestore handles indexes and foreign keys of the column being modified, couldn't find anything related on [the docs](https://docs.singlestore.com/cloud/reference/sql-reference/data-definition-language-ddl/alter-table/#alter-table-to-modify-column-data-types-sizes-and-collation).

### CODE REVIEW

File: src/Schema/Grammar.php [hunk 1]
```diff
@@ -25,6 +27,61 @@ public function __construct()
...
+     * @param  \Illuminate\Support\Fluent  $command
+     * @param  \Illuminate\Database\Connection  $connection
+     * @return array|string
+     *
+     * @throws \RuntimeException
+     */
+    public function compileChange(Blueprint $blueprint, Fluent $command, Connection $connection)
+    {
+        if (version_compare(Application::VERSION, '10.0', '<')) {
+            throw new LogicException('This database driver does not support modifying columns on Laravel < 10.0.');
```
Comment (AdalbertMemSQL) [inline src/Schema/Grammar.php:43]: What is the reason, why this is not supported for older versions of Laravel?

Comment (hafezdivandari) [reply src/Schema/Grammar.php:43]: Older Laravel versions doesn't support native column modifying, you may check:
* laravel/framework#45487
* laravel/framework#48864

Laravel was using `doctrine/dbal` before this version and I'm quit sure that it is going to be a problem for your package as Doctrine DBAL doesn't support Singlestore. But you may add tests to see if it fallbacks to MySQL correctly or not.

Comment (hafezdivandari) [reply src/Schema/Grammar.php]: in the latest commit 9777d8a I removed this and added test to see if it works with lower Laravel version + Doctrine DBAL

Comment (AdalbertMemSQL) [reply src/Schema/Grammar.php]: Thanks!

Comment (hafezdivandari) [reply src/Schema/Grammar.php]: OK the tests shows that we can't use doctrine: 

> SQLSTATE[HY000]: General error: 1706 Feature 'ALTER TABLE CHANGE to modify column type' is not supported by SingleStore. Use MODIFY to change a column's type. (Connection: mysql, SQL: ALTER TABLE test CHANGE data data TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`)

**Comment by AdalbertMemSQL** [comment]
It looks like `Schema::getColumnType` requires `Doctrine\DBAL\Driver\AbstractMySQLDriver` for 10.0.0 version of Laravel.
But from 10.30.0 it works well (https://github.com/laravel/framework/pull/48357 )

**Comment by hafezdivandari** [comment]
@AdalbertMemSQL yeah I fixed that function on Laravel 10.30, it was using Doctrine DBAL before that. We can limit that assertion to latest version maybe?

**Comment by AdalbertMemSQL** [comment]
Yep, that sounds like a good solution
